// NEXT_PUBLIC_ADMIN_EMAIL=admin@test.com
// NEXT_PUBLIC_ADMIN_PASSWORD=123456
// NEXT_PUBLIC_RETAILER_EMAIL=retailer@test.com
// NEXT_PUBLIC_RETAILER_PASSWORD=123456
// JWT_SECRET=difwa_secret_key_123
