// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGx-JoxvVU6Ag-GoJyZd--IjjsJbOEpvQ',
    appId: '1:501607990708:web:c4843b280e0e57da07dee1',
    messagingSenderId: '501607990708',
    projectId: 'difwa-continue',
    authDomain: 'difwa-continue.firebaseapp.com',
    storageBucket: 'difwa-continue.firebasestorage.app',
    measurementId: 'G-S2CK0RM7NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCv2HwmS1TPAJUMBwhtkV9Xrc4LUgg6D8',
    appId: '1:685191561219:android:e74a67b4d2c23a13e9ce36',
    messagingSenderId: '685191561219',
    projectId: 'codechat-45ec2',
    storageBucket: 'codechat-45ec2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-ITSfCWmUzloO_5nLad5DietFjZVNoHk',
    appId: '1:501607990708:ios:934f13181fd41c3a07dee1',
    messagingSenderId: '501607990708',
    projectId: 'difwa-continue',
    storageBucket: 'difwa-continue.firebasestorage.app',
    iosBundleId: 'com.difmo.difwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-ITSfCWmUzloO_5nLad5DietFjZVNoHk',
    appId: '1:501607990708:ios:6181875979b85f5b07dee1',
    messagingSenderId: '501607990708',
    projectId: 'difwa-continue',
    storageBucket: 'difwa-continue.firebasestorage.app',
    iosBundleId: 'com.example.liciusApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGx-JoxvVU6Ag-GoJyZd--IjjsJbOEpvQ',
    appId: '1:501607990708:web:b9abbafe55ef43f907dee1',
    messagingSenderId: '501607990708',
    projectId: 'difwa-continue',
    authDomain: 'difwa-continue.firebaseapp.com',
    storageBucket: 'difwa-continue.firebasestorage.app',
    measurementId: 'G-QWNW1VW9BV',
  );
}
