// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// sd
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq9Bq2fOQOksFyzrUS0-qy94RyXiPmT44',
    appId: '1:678567433966:android:331761fa4e78374230c5ff',
    messagingSenderId: '678567433966',
    projectId: 'device-streaming-4328d08d',
    storageBucket: 'device-streaming-4328d08d.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpAOr6_Kk6Y96qGfEm6y50QJs76b5_i7o',
    appId: '1:678567433966:web:184339a1e76782b730c5ff',
    messagingSenderId: '678567433966',
    projectId: 'device-streaming-4328d08d',
    authDomain: 'device-streaming-4328d08d.firebaseapp.com',
    storageBucket: 'device-streaming-4328d08d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-JL-o1KErIMGtAhWDC09o4lRVKCS7Itw',
    appId: '1:678567433966:ios:a6dfea98a5e3e10430c5ff',
    messagingSenderId: '678567433966',
    projectId: 'device-streaming-4328d08d',
    storageBucket: 'device-streaming-4328d08d.firebasestorage.app',
    iosBundleId: 'com.example.hello',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-JL-o1KErIMGtAhWDC09o4lRVKCS7Itw',
    appId: '1:678567433966:ios:a139f55d7b404d4f30c5ff',
    messagingSenderId: '678567433966',
    projectId: 'device-streaming-4328d08d',
    storageBucket: 'device-streaming-4328d08d.firebasestorage.app',
    iosBundleId: 'com.shrimpbite.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpAOr6_Kk6Y96qGfEm6y50QJs76b5_i7o',
    appId: '1:678567433966:web:cb41096c2a6463ba30c5ff',
    messagingSenderId: '678567433966',
    projectId: 'device-streaming-4328d08d',
    authDomain: 'device-streaming-4328d08d.firebaseapp.com',
    storageBucket: 'device-streaming-4328d08d.firebasestorage.app',
  );

}